### ISSUE TITLE
Building the library example

### ISSUE THREAD

**Issue by chrisbuttery** [duojs/test#56]
All the duo-test(1) examples rely on a `build.js` file being located in the root.

I'm looking at the [Library example](https://github.com/duojs/test/tree/master/examples/library) in particular and wondering if it's possible to have the tests reference `build/build.js` instead of `build.js`.

Im a noob to Makefiles and duo-test, so apologies if this is obvious.

```
T = ./node_modules/duo-test/bin/duo-test
TESTS = $(filter-out test/tests.js, $(wildcard test/*.js))
SRC = $(wildcard index.js lib/**/*.js)

build.js: test/tests.js
    duo --root . --type js < $< > $@

test/tests.js: $(SRC) $(TESTS)
    @echo '// GENERATED FILE: DO NOT EDIT!' > $@
    @$(foreach test, $(TESTS), echo 'require("./$(test)");' >> $@;)

test: test-phantomjs

test-phantomjs: build.js
    @$(T) phantomjs --reporter spec

test-browser: build.js
    @$(T) browser

test-saucelabs: build.js
    @$(T) saucelabs -b safari:6..7

clean:
    rm -rf test/tests.js build.js components

.PHONY: clean test test-phantomjs test-browser
```

**Comment by chrisbuttery** [comment]
@dominicbarnes Sorry to dig up an old issue to ask, but can you tell me what Makefile book Lance was referring to in this post ? https://github.com/duojs/test/issues/56#issuecomment-61228277

**Comment by dominicbarnes** [comment]
iirc, it was [this one](https://www.amazon.com/gp/product/B0026OR2RW/) (Managing Projects with GNU Make)

**Comment by chrisbuttery** [comment]
Awesome. Thank you.
